### ISSUE TITLE
Incorrect parameter checking in user.js

### ISSUE THREAD

**Issue by jonascheng** [trendmicro/serverless-survey-forms#11]
@phejimlin line 42 should be SERVERLESS_USERTABLE instead of SERVERLESS_SURVEYTABLE.

Please take your time to fix it. Thanks!

**Comment by phejimlin** [comment]
ok!! Got it!

**Comment by jonascheng** [comment]
Ha ha, I may fix this today otherwise I could not continue my work. :)

**Comment by jonascheng** [comment]
fixed in a 16007aa0c4420295cfc114ca6bb156202eedc1c
